name: Page Speed Insights
on: [push]

jobs:
  run_psi:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Running Page Speed Insights
      id: psi
      uses: jakepartusch/psi-action@v1.3
      with:
          url: 'https://atomtr.link/'
          key: ${{ secrets.PSI_API_KEY }}
          strategy: desktop
